// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package TimeRules

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (DateObj) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*DateObj) UnmarshalJSON([]byte) error        { return nil }
func (DateObj) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*DateObj) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DateObj *DateObj

func (DateTimeObj) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*DateTimeObj) UnmarshalJSON([]byte) error        { return nil }
func (DateTimeObj) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*DateTimeObj) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_DateTimeObj *DateTimeObj

func (TimeObj) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*TimeObj) UnmarshalJSON([]byte) error        { return nil }
func (TimeObj) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*TimeObj) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TimeObj *TimeObj
