// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package TimeRules

import (
	"github.com/mailru/easyjson/jlexer"
	"github.com/mailru/easyjson/jwriter"
)

func (FormatsInfoObj) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*FormatsInfoObj) UnmarshalJSON([]byte) error        { return nil }
func (FormatsInfoObj) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*FormatsInfoObj) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_FormatsInfoObj *FormatsInfoObj

func (MonthObj) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*MonthObj) UnmarshalJSON([]byte) error        { return nil }
func (MonthObj) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*MonthObj) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_MonthObj *MonthObj

func (SystemInfoObj) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*SystemInfoObj) UnmarshalJSON([]byte) error        { return nil }
func (SystemInfoObj) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*SystemInfoObj) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_SystemInfoObj *SystemInfoObj

func (TimeConfigurationRulesObj) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*TimeConfigurationRulesObj) UnmarshalJSON([]byte) error        { return nil }
func (TimeConfigurationRulesObj) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*TimeConfigurationRulesObj) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TimeConfigurationRulesObj *TimeConfigurationRulesObj

func (YearLimitsObj) MarshalJSON() ([]byte, error)       { return nil, nil }
func (*YearLimitsObj) UnmarshalJSON([]byte) error        { return nil }
func (YearLimitsObj) MarshalEasyJSON(w *jwriter.Writer)  {}
func (*YearLimitsObj) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_YearLimitsObj *YearLimitsObj
